### ISSUE TITLE
Request for more details about compilation and hardware generation

### ISSUE THREAD

**Issue by Ivecia** [IBM/NOVIA#7]
Thanks for your amazing work!

I have noticed that novia-1.5.0 has been updated several months ago, and I'm trying to reproduce the result of your paper. I have tried the newest commit of novia-1.5.0, and it seems that some scripts are broken and novia may crash sometimes.

Could you please provide more information about the compilation and hardware generation parts? Thanks in advance!

**Comment by Ivecia** [comment]
Problems I have met are:
- Script error: `/opt/NOVIA/fusion/analysis/scripts/testing.sh: No such file or directory`
https://github.com/IBM/NOVIA/blob/7f388e07c0c5fb7d3cd4ddc74197d14e38e6a9f1/fusion/analysis/scripts/novia.sh#L130
- `opt: /opt/NOVIA/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Instruction; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Instruction*]: Assertion isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.`
- Some of the process may output A LOT OF `half` or some big negative number
- Can not validate the NFU using ariane core (after fixing some errors)

**Comment by davidtrilla** [comment]
Hello! First of all thanks for your interest, and sorry for the late reply, I've been away from IBM for a few months and I didn't have access to my IBM email account so I couldn't get notified.

The 1.5 update was a rushed effort to push all the work that was in the WIP before I lost access to the source code, hence why some of the scripts and tests might be broken. 

- for testing.sh I probably forgot to push that one, it was work in progress so not much in there yet, the goal was to have a test script that would execute a software novia modified version of the llvm-ir against a regular version and check for output correctness.
- This probably is a merged instruction that probably shouldn't be getting merged becuase of incompatible operands, but I can't say much more without the use case, is it using one of the examples ? or is it your own ? Pretty  much the same with the rest of the points, can you share your use-case?
- What do you mean exactly by validating the NFU core?

**Comment by Ivecia** [comment]
Sorry to hear that you've been away from IBM. And never mind for the late reply. I'm working on a new "backend" framework to generate the LLVM patch and maybe the hardware patch for evaluating "frontend" instructions merging process or some kinds of processes like that. 

- **Can you share your use-case?** The use-case was [dependency](https://github.com/IBM/NOVIA/tree/novia-1.5.0/fusion/examples/dependency) in your 1.5 update, without any modification. (I will reproduce the merging process later, and replace the compilation process with my own LLVM patch)
- **What do you mean exactly by validating the NFU core?** I tried to patch the Ariane core with your patches, and got errors on verilator runs. (May be there were some mistakes made by myself?)

Since I'm going to use NOVIA as a "frontend" process case. So, maybe I'll look more deeper into your repo and provide more information to you later.

**Comment by davidtrilla** [comment]
This is interesting, since it's one of the example use cases, give me a few days to rebuild and test and see what the problem might be, maybe I can patch the error or at the very least tell you what's going on.  

W.r.t. the ariane core, are those real errors? just some warnings? the NFU implementation should not interfere with any other core functionality, the other tests should be unaffected, I will certainly try this myself.

**Comment by Ivecia** [comment]
Thanks in advance! I'm not sure where these errors came from for now, since it's several weeks ago. Maybe there are some mistakes.

By the way, the `opt` error may sometimes happen and sometimes it may not, quite strange. I suggest you enable the debug mode (in your config file) and see what will happen.

Anyway, I'll try to rebuild 1.5 later, and provide more information to you.

**Comment by Ivecia** [comment]
I rebuild your 1.5 update, and find that `incremental` works well, but `dependency` outputs the `opt` error. (And I have edited the use-case link in previous comment, sorry for mistake.)

Full log:
```
root@icarus4:/opt/NOVIA/fusion/examples/dependency# novia dependency.bc 
Starting Novia Analysis:
Using default performance threshold (0.8)
############################################################################################
Analyzing dependency: Preparation phase
############################################################################################
ok
Optimizing Memory: done
Renaming Pre-inline: done
Instrumenting Pre-inline: done
Linking Timers and Compiling Pre-inline: done
Profiling Pre-inline: ./bin/dependency_ins.bin 1:Result: -4199008
done
Processing Histogram Pre-inline:
Inlining: done
Instrumenting Post-inline: done
Linking Timers and Compiling Post-inline: done
Profiling Post-inline: ./bin/dependency_ins_inl.bin 1:Result: -4199072
done
Processing Histogram Post-inline:
############################################################################################
Analyzing dependency - Merge phase: 
NFU file does not exist, implementing all inline accelerators
############################################################################################
NFU Implementation File missing or not specified; All NFUs will be implemented. Continuing.
Visualization directory does not exist - creating it...
opt: /opt/NOVIA/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Instruction; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Instruction*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/NOVIA/llvm-project/build/bin//opt -enable-new-pm=0 -load /opt/NOVIA/fusion/build/lib//libfusionlib.so -mergeBBList -bbs data/bblist_inl.txt --dynInf data/weights_inl.txt --graph_dir imgs --visualFormat png --visualLevel 7 --nfus data/nfu.txt
1.	Running pass 'Merge BBs' on module '<stdin>'.
 #0 0x00007f593be9c7c4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00007f593be99fde SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f593b929090 (/lib/x86_64-linux-gnu/libc.so.6+0x43090)
 #3 0x00007f593b92900b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f593b908859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00007f593b908729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #6 0x00007f593b919fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #7 0x00007f593a954989 llvm::cast_retty<llvm::Instruction, llvm::Value*>::ret_type llvm::cast<llvm::Instruction, llvm::Value>(llvm::Value*) /opt/NOVIA/llvm-project/llvm/include/llvm/Support/Casting.h:269:3
 #8 0x00007f593a98adc2 FusedBB::insertInlineCall(llvm::Function*, std::map<llvm::Value*, llvm::Value*, std::less<llvm::Value*>, std::allocator<std::pair<llvm::Value* const, llvm::Value*> > >*, int, bool) /opt/NOVIA/fusion/src/types/FusedBB.cpp:1064:35
 #9 0x00007f593a916763 (anonymous namespace)::mergeBBList::runOnModule(llvm::Module&) /opt/NOVIA/fusion/src/fuseLibraryPass.cpp:504:43
#10 0x00007f593c11b6c0 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/NOVIA/llvm-project/build/bin/../lib/libLLVMCore.so.13+0x2286c0)
#11 0x00005574510d0bc7 main (/opt/NOVIA/llvm-project/build/bin//opt+0x26bc7)
#12 0x00007f593b90a083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#13 0x00005574510d171e _start (/opt/NOVIA/llvm-project/build/bin//opt+0x2771e)
/opt/NOVIA/fusion/analysis/scripts/merge.sh: line 27:   156 Aborted                 (core dumped) $LLVM_BIN/opt -enable-new-pm=0 -load $FUSE_LIB/libfusionlib.so -mergeBBList -bbs "data/bblist_inl.txt" --dynInf "data/weights_inl.txt" --graph_dir imgs --visualFormat $NOVIA_VIZ_FORMAT --visualLevel $NOVIA_VIZ_LVL --nfus "data/nfu.txt" < $name_inl > $name_novia
Generated inlined bitcode file (output/dependency_novia.bc)
Generated merge/split statistics (data/stats.csv)
Source code locations (data/source.log)
Generated DFG images (imgs/)
############################################################################################
Analyzing dependency - Pre-merge Report:
############################################################################################
Traceback (most recent call last):
  File "/opt/NOVIA/fusion/analysis/scripts/preanalysis.py", line 59, in <module>
    main(sys.argv[1:])
  File "/opt/NOVIA/fusion/analysis/scripts/preanalysis.py", line 11, in main
    fsource = open(argv[2],'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/source.log'
############################################################################################
Analyzing dependency - Post-merge Report:
############################################################################################
Traceback (most recent call last):
  File "/opt/NOVIA/fusion/analysis/scripts/postanalysis.py", line 67, in <module>
    main(sys.argv[1:])
  File "/opt/NOVIA/fusion/analysis/scripts/postanalysis.py", line 12, in main
    fsource = open(argv[3],'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/source.log'
/opt/NOVIA/fusion/bin/novia: line 130: /opt/NOVIA/fusion/analysis/scripts/testing.sh: No such file or directory
```
